-- Dubuhub - Raw text hosting for loadstring
-- Usage: loadstring(game:HttpGet("https://dubuhub.vercel.app/YOUR_PASTE_ID"))()
--
-- Create a paste:
--   POST https://dubuhub.vercel.app/api/paste
--   JSON: { "content": "your lua script here" }
--
-- Response: { "id": "abc123", "rawUrl": "https://dubuhub.vercel.app/abc123", ... }
--
-- Then use:
-- loadstring(game:HttpGet("https://dubuhub.vercel.app/abc123"))()
